In [1]:
import tensorflow as tf
print(tf.__version__)

2.4.1


# Housing Prediction

In this exercise you'll try to build a neural network that predicts the price of a house according to a simple formula.

So, imagine if house pricing was as easy as a house costs 50k + 50k per bedroom, so that a 1 bedroom house costs 100k, a 2 bedroom house costs 150k etc.

How would you create a neural network that learns this relationship so that it would predict a 7 bedroom house as costing close to 400k etc.

Hint: Your network might work better if you scale the house price down. You don't have to give the answer 400...it might be better to create something that predicts the number 4, and then your answer is in the 'hundreds of thousands' etc.

In [6]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np

In [9]:
def housing_price(y_new):
    xs = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], dtype=float)
    ys = np.array([1.0, 1.5, 2.0, 2.5, 3.0, 3.5], dtype=float)
    model = tf.keras.Sequential([tf.keras.layers.Dense(units=1,input_shape=[1])])
    model.compile(optimizer="sgd",loss="mean_squared_error")
    model.fit(xs,ys,epochs=100)
    return model.predict(y_new)[0]

In [10]:
housing_price([7])

Epoch 1/100
1/1 [==============================] - 0s 428ms/step - loss: 28.2596
Epoch 2/100
1/1 [==============================] - 0s 8ms/step - loss: 13.0834
Epoch 3/100
1/1 [==============================] - 0s 7ms/step - loss: 6.0593
Epoch 4/100
1/1 [==============================] - 0s 8ms/step - loss: 2.8084
Epoch 5/100
1/1 [==============================] - 0s 9ms/step - loss: 1.3037
Epoch 6/100
1/1 [==============================] - 0s 9ms/step - loss: 0.6073
Epoch 7/100
1/1 [==============================] - 0s 11ms/step - loss: 0.2849
Epoch 8/100
1/1 [==============================] - 0s 6ms/step - loss: 0.1357
Epoch 9/100
1/1 [==============================] - 0s 6ms/step - loss: 0.0666
Epoch 10/100
1/1 [==============================] - 0s 4ms/step - loss: 0.0346
Epoch 11/100
1/1 [==============================] - 0s 3ms/step - loss: 0.0197
Epoch 12/100
1/1 [==============================] - 0s 5ms/step - loss: 0.0128
Epoch 13/100
1/1 [==============================] - 0s 4

array([4.0870605], dtype=float32)

In [16]:
y_new=[7,9,10]
def housing_price(y_new):
    xs = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], dtype=float)
    ys = np.array([1.0, 1.5, 2.0, 2.5, 3.0, 3.5], dtype=float)
    model = tf.keras.Sequential([tf.keras.layers.Dense(units=1,input_shape=[1])])
    model.compile(optimizer="sgd",loss="mean_squared_error")
    model.fit(xs,ys,epochs=100)
    return model.predict(y_new)

In [17]:
housing_price(y_new)

Epoch 1/100
1/1 [==============================] - 0s 420ms/step - loss: 3.4590
Epoch 2/100
1/1 [==============================] - 0s 8ms/step - loss: 1.6168
Epoch 3/100
1/1 [==============================] - 0s 8ms/step - loss: 0.7641
Epoch 4/100
1/1 [==============================] - 0s 6ms/step - loss: 0.3693
Epoch 5/100
1/1 [==============================] - 0s 8ms/step - loss: 0.1865
Epoch 6/100
1/1 [==============================] - 0s 9ms/step - loss: 0.1017
Epoch 7/100
1/1 [==============================] - 0s 7ms/step - loss: 0.0624
Epoch 8/100
1/1 [==============================] - 0s 7ms/step - loss: 0.0441
Epoch 9/100
1/1 [==============================] - 0s 7ms/step - loss: 0.0355
Epoch 10/100
1/1 [==============================] - 0s 7ms/step - loss: 0.0314
Epoch 11/100
1/1 [==============================] - 0s 8ms/step - loss: 0.0294
Epoch 12/100
1/1 [==============================] - 0s 9ms/step - loss: 0.0284
Epoch 13/100
1/1 [==============================] - 0s 9ms/

array([[4.173876 ],
       [5.3017826],
       [5.865736 ]], dtype=float32)

In [18]:
housing_price([7])

Epoch 1/100
1/1 [==============================] - 0s 405ms/step - loss: 32.0049
Epoch 2/100
1/1 [==============================] - 0s 9ms/step - loss: 14.8161
Epoch 3/100
1/1 [==============================] - 0s 10ms/step - loss: 6.8605
Epoch 4/100
1/1 [==============================] - 0s 8ms/step - loss: 3.1784
Epoch 5/100
1/1 [==============================] - 0s 7ms/step - loss: 1.4742
Epoch 6/100
1/1 [==============================] - 0s 11ms/step - loss: 0.6855
Epoch 7/100
1/1 [==============================] - 0s 9ms/step - loss: 0.3204
Epoch 8/100
1/1 [==============================] - 0s 8ms/step - loss: 0.1514
Epoch 9/100
1/1 [==============================] - 0s 8ms/step - loss: 0.0731
Epoch 10/100
1/1 [==============================] - 0s 12ms/step - loss: 0.0369
Epoch 11/100
1/1 [==============================] - 0s 6ms/step - loss: 0.0201
Epoch 12/100
1/1 [==============================] - 0s 8ms/step - loss: 0.0123
Epoch 13/100
1/1 [==============================] - 0s

array([[4.0785007]], dtype=float32)

# classification using Fashion MNIST without convolutions(Basic NN)

Exercise 2
In the course you learned how to do classification using Fashion MNIST, a data set containing items of clothing. There's another, similar dataset called MNIST which has items of handwriting -- the digits 0 through 9.

Write an MNIST classifier that trains to 99% accuracy or above, and does it without a fixed number of epochs -- i.e. you should stop training once you reach that level of accuracy.

Some notes:

It should succeed in less than 10 epochs, so it is okay to change epochs to 10, but nothing larger
When it reaches 99% or greater it should print out the string "Reached 99% accuracy so cancelling training!"
If you add any additional variables, make sure you use the same names as the ones used in the class
I've started the code for you below -- how would you finish it?

In [19]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist

In [23]:
def train_mnist():
    class myCallback(tf.keras.callbacks.Callback):
      def on_epoch_end(self, epoch, logs={}):
        if(logs.get('accuracy')>0.99):
          print("\nReached 99% accuracy so cancelling training!")
          self.model.stop_training = True
    mnist = tf.keras.datasets.mnist
    (x_train, y_train),(x_test, y_test) = mnist.load_data()
    x_train , x_test = x_train/255.0 , x_test/255.0
    callbacks = myCallback()
    
    model = tf.keras.Sequential([
        tf.keras.layers.Flatten(input_shape=(28,28)),
        tf.keras.layers.Dense(1028,activation = tf.nn.relu),
        tf.keras.layers.Dense(10,activation = tf.nn.softmax)
    ])
    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    history = model.fit(x_train, y_train,epochs=10, callbacks=[callbacks])
    return history.epoch ,history.history['accuracy'][-1]

In [24]:
train_mnist()

Epoch 1/10
1875/1875 [==============================] - 19s 10ms/step - loss: 0.3166 - accuracy: 0.9045
Epoch 2/10
1875/1875 [==============================] - 18s 9ms/step - loss: 0.0782 - accuracy: 0.9753
Epoch 3/10
1875/1875 [==============================] - 18s 10ms/step - loss: 0.0458 - accuracy: 0.9857
Epoch 4/10
1875/1875 [==============================] - 17s 9ms/step - loss: 0.0322 - accuracy: 0.9901
Epoch 5/10
1875/1875 [==============================] - 18s 10ms/step - loss: 0.0217 - accuracy: 0.9929

Reached 99% accuracy so cancelling training!


([0, 1, 2, 3, 4], 0.991183340549469)

# classification using Fashion MNIST using convolutions to avoid overfitting

In the videos you looked at how you would improve Fashion MNIST using Convolutions. For your exercise see if you can improve MNIST to 99.8% accuracy or more using only a single convolutional layer and a single MaxPooling 2D. You should stop training once the accuracy goes above this amount. It should happen in less than 20 epochs, so it's ok to hard code the number of epochs for training, but your training must end once it hits the above metric. If it doesn't, then you'll need to redesign your layers.

I've started the code for you -- you need to finish it!

When 99.8% accuracy has been hit, you should print out the string "Reached 99.8% accuracy so cancelling training!"

In [39]:
def fashion_mnist():
    class myCallback(tf.keras.callbacks.Callback):
      def on_epoch_end(self, epoch, logs={}):
        if(logs.get('accuracy')>0.99):
          print("\nReached 99% accuracy so cancelling training!")
          self.model.stop_training = True
    
    mnist = tf.keras.datasets.mnist
    (train_images , train_labels) , (test_images ,test_labels) = mnist.load_data()
    train_images = train_images.reshape(60000,28,28,1)
    train_images = train_images/255.0
    test_images = test_images.reshape(10000,28,28,1)
    test_images = test_images/255.0
    
    callbacks = myCallback()
    
    model = tf.keras.Sequential([
        tf.keras.layers.Conv2D(32, (3,3), activation='relu', input_shape=(28, 28, 1)),
        tf.keras.layers.MaxPooling2D(2, 2),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(128,activation='relu'),
        tf.keras.layers.Dense(10,activation='softmax')
    ])
    
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    
    history = model.fit (train_images, train_labels, epochs=10, callbacks=[callbacks])
    model.evaluate(test_images, test_labels)
    return history.epoch,history.history['accuracy'][-1]

In [40]:
fashion_mnist()

Epoch 1/10
1875/1875 [==============================] - 44s 23ms/step - loss: 0.3018 - accuracy: 0.9117
Epoch 2/10
1875/1875 [==============================] - 44s 23ms/step - loss: 0.0502 - accuracy: 0.9849
Epoch 3/10
1875/1875 [==============================] - 42s 22ms/step - loss: 0.0308 - accuracy: 0.9901
Epoch 4/10
1875/1875 [==============================] - 48s 26ms/step - loss: 0.0183 - accuracy: 0.9949

Reached 99% accuracy so cancelling training!
313/313 [==============================] - 3s 8ms/step - loss: 0.0447 - accuracy: 0.9858


([0, 1, 2, 3], 0.9937999844551086)

# CNN with happy or sad data set

Below is code with a link to a happy or sad dataset which contains 80 images, 40 happy and 40 sad. Create a convolutional neural network that trains to 100% accuracy on these images, which cancels training upon hitting training accuracy of >.999

Hint -- it will work best with 3 convolutional layers.

In [41]:
"""
!curl https://storage.googleapis.com/laurencemoroney-blog.appspot.com/happy-or-sad.zip \
    -O "E:/TensorflowDeveloperCertification/Learning/validation-horse-or-human.zip" 

!wget --no-check-certificate \
    "https://storage.googleapis.com/laurencemoroney-blog.appspot.com/happy-or-sad.zip" \
    -O "/tmp/happy-or-sad.zip"

"""

'\n!curl https://storage.googleapis.com/laurencemoroney-blog.appspot.com/happy-or-sad.zip     -O "E:/TensorflowDeveloperCertification/Learning/validation-horse-or-human.zip" \n\n!wget --no-check-certificate     "https://storage.googleapis.com/laurencemoroney-blog.appspot.com/happy-or-sad.zip"     -O "/tmp/happy-or-sad.zip"\n\n'

In [42]:
pwd

'E:\\TensorflowDeveloperCertification\\dlaicourse-master\\Exercises\\Exercise 1 - House Prices'

In [45]:
import os
os.chdir("E:\\TensorflowDeveloperCertification\\")

In [58]:
import requests, zipfile, io
zip_file_url = 'https://storage.googleapis.com/laurencemoroney-blog.appspot.com/happy-or-sad.zip'
r = requests.get(zip_file_url)
z = zipfile.ZipFile(io.BytesIO(r.content))
z.extractall("E:\\TensorflowDeveloperCertification\\happy-or-sad")

In [63]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import requests, zipfile, io
from tensorflow.keras.optimizers import RMSprop

def happyorsad():
    zip_file_url = 'https://storage.googleapis.com/laurencemoroney-blog.appspot.com/happy-or-sad.zip'
    r = requests.get(zip_file_url)
    z = zipfile.ZipFile(io.BytesIO(r.content))
    z.extractall("E:\\TensorflowDeveloperCertification\\happy-or-sad")
    
    DESIRED_ACCURACY = 0.999
    class myCallback(tf.keras.callbacks.Callback):
      def on_epoch_end(self, epoch, logs={}):
        if(logs.get('acc')>DESIRED_ACCURACY):
          print("\nReached 99.9% accuracy so cancelling training!")
          self.model.stop_training = True
    
    train_datagen = ImageDataGenerator(rescale=1/255)

    train_generator = train_datagen.flow_from_directory(
        "E:\\TensorflowDeveloperCertification\\happy-or-sad",  
        target_size=(150, 150), 
        batch_size=10,
        class_mode='binary')
    
    callbacks = myCallback()
    
    model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(16, (3,3), activation='relu', input_shape=(150, 150, 3)),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Conv2D(32, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Conv2D(32, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')])
    
    model.compile(loss='binary_crossentropy',
              optimizer=RMSprop(lr=0.001),
              metrics=['acc'])
    history = model.fit_generator(
      train_generator,
      steps_per_epoch=2,  
      epochs=15,
      verbose=1,
      callbacks=[callbacks])
    return history.epoch,history.history['acc'][-1]    


In [64]:
happyorsad()

Found 80 images belonging to 2 classes.
Epoch 1/15
2/2 [==============================] - 2s 244ms/step - loss: 3.4798 - acc: 0.5000
Epoch 2/15
2/2 [==============================] - 0s 228ms/step - loss: 1.0268 - acc: 0.5000
Epoch 3/15
2/2 [==============================] - 0s 238ms/step - loss: 0.5429 - acc: 0.7000
Epoch 4/15
2/2 [==============================] - 0s 229ms/step - loss: 0.4122 - acc: 0.9333
Epoch 5/15
2/2 [==============================] - 0s 229ms/step - loss: 0.4370 - acc: 0.7667
Epoch 6/15
2/2 [==============================] - 0s 228ms/step - loss: 0.4625 - acc: 0.6333
Epoch 7/15
2/2 [==============================] - 0s 237ms/step - loss: 0.2592 - acc: 0.9000
Epoch 8/15
2/2 [==============================] - 0s 228ms/step - loss: 0.1475 - acc: 0.9333
Epoch 9/15
2/2 [==============================] - 0s 228ms/step - loss: 0.2396 - acc: 0.9333
Epoch 10/15
2/2 [==============================] - 1s 243ms/step - loss: 0.2341 - acc: 0.9333
Epoch 11/15
2/2 [============

([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 1.0)